### ISSUE TITLE
Support for rxgrpc

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-grpc#15] opened 2017-10-19 11:49 UTC
https://github.com/salesforce/grpc-java-contrib/blob/master/rxgrpc/README.md

**Comment by vietj** [comment] 2018-03-29 14:12
https://github.com/salesforce/reactive-grpc

**Comment by pmlopes** [comment] 2019-02-13 19:20
- [ ] implement a vertx-plugin like https://github.com/salesforce/reactive-grpc/tree/master/reactor or use rx directly
- [ ] remove custom https://github.com/vert-x3/vertx-grpc-java-compiler
- [ ] repackage netty from grpc into a different location in a shaded jar to avoid conflict with core

**Comment by rogelio-o** [comment] 2019-07-28 11:04
I’m starting to work on this. Would you like that the plugin would be implemented in the vertx-grpc-java-compiler repository or where would be a good place?

**Comment by vietj** [comment] 2019-07-28 16:20
@rogelio-o we discontinue the vertx-grpc-java-compiler project in 4.0 (too complicated to maintain) so it would be a new project or perhaps it could be in vertx-rx ?

**Comment by rogelio-o** [comment] 2019-07-28 17:01
My idea is to do it using Future, Handler and ReadStream/WriteStream instead of Rx types, so maybe a new project would be the best option.

**Comment by indiketa** [comment] 2019-07-31 15:19
I've implemented a plugin  that generates the serviceVertxStub and serviceVertxImplBase classes. 

As @pmlopes suggests, I've followed the salesforce plugin:
https://github.com/salesforce/reactive-grpc

I have two questions:

1. Is possible to add the Handler to StreamObserver code in this vertx-grpc project? Currently each generated service includes the method to do this conversion [not very elegant] (code generated by vertx-grpc-java-compiler). Adding a GrpcStreamObserverExchange.

2. Where can i commit / pr this plugin? I think it could be a new project (only needed in compilation/generation phase)

**Comment by rogelio-o** [comment] 2019-07-31 18:13
@indiketa, if you've implemented the backpressure (AbstractSubscriberAndProducer) in the vertx-grpc, go on. I had implemented the plugin to generate the classes (like in reactive-grpc) as I said but I have still to implement the backpressure in the vertx-grpc. My generated classes aren't valid until the backpressure utils wold be implemented in vertx-grpc.

**Comment by indiketa** [comment] 2019-07-31 18:31
No no ;)

At the moment I developed the same functionality that vertx-grpc-java-compiler did to a plugin that generates the same vertx3 code. I have to implement the vertx4 "futurisation" and remove deprecated code.

But for now, it works. I think that backpressure algo over grpc is out of my scope.

I've commited to:
https://github.com/indiketa/vertx-grpc-plugin

**Comment by rogelio-o** [comment] 2019-07-31 19:19
We are working on different approachs. What I'm working in (https://github.com/rogelio-o/vertx-grpc-protoc-plugin) is in a plugin following the same philosophy of salesforce/reactive-grpc (delegation and adaptation) and that can be used as protocPlugin. For that, the "adapters" should be added to the vertx-grpc project (https://github.com/rogelio-o/vertx-grpc/tree/issues/15-support-for-rxgrpc/src/main/java/io/vertx/grpc/stub). In the "adapters", I want to implement the backpressure, but it's been busy days. Hopefully, this weekend I could finish the work.

**Comment by rogelio-o** [comment] 2019-08-03 17:30
@vietj, I've pushed the plugin with some examples to: https://github.com/rogelio-o/vertx-grpc-protoc-plugin

The generated service stubs works with the vertx-grpc library of this branch: https://github.com/rogelio-o/vertx-grpc/tree/issues/15-support-for-rxgrpc. Notice that some classes would be deprecated.

An option could be make the vertx-grpc repository multi-module (like vertx-web) so we can add in that repository the plugin and the examples.

Just let me know how to proceed. I'll open the PR on vertx-grpc at the same time that the PR with the plugin.

**Comment by vietj** [comment] 2019-08-04 17:13
@indiketa how does one execute your plugin ? I don't see any test or how-to

**Comment by vietj** [comment] 2019-08-04 17:17
@rogelio-o if I understand correctly your plugin would offer the same features than the current vertx-grpc-java-compiler but written in java using the salesforce plugin ?

**Comment by vietj** [comment] 2019-08-04 17:18
@indiketa your approach looks very simple (which is nice) but I can't see any example

**Comment by rogelio-o** [comment] 2019-08-04 18:13
@vietj it doesn't use the salesforce compiler, it's a protocPlugin like the salesforce compiler. The salesforce compiler creates proto classes using RxJava, the vertx-grpc-protoc-plugin creates classes using Vertx components (Future, ReadStream,...). This is the same than with the vertx-grpc-java-compiler, but with one important different. The pattern following here is delegation: the created classes use the original gRPC classes and translate gRPC components to Vertx components. This translations are made with two new classes added to vertx-grpc (https://github.com/rogelio-o/vertx-grpc/blob/issues/15-support-for-rxgrpc/src/main/java/io/vertx/grpc/stub/ClientCalls.java and https://github.com/rogelio-o/vertx-grpc/blob/issues/15-support-for-rxgrpc/src/main/java/io/vertx/grpc/stub/ServerCalls.java). The goal here is reduce what the generated code does.

This is an example of what the plugin generates: https://github.com/rogelio-o/vertx-grpc/blob/issues/15-support-for-rxgrpc/src/main/java/examples/VertxGreeterGrpc.java

You can see also the tests updates using the new generated classes: https://github.com/rogelio-o/vertx-grpc/blob/issues/15-support-for-rxgrpc/src/test/java/io/vertx/ext/grpc/GoogleTest.java

And the pom with the plugin configuration updated: https://github.com/rogelio-o/vertx-grpc/blob/issues/15-support-for-rxgrpc/pom.xml

Also, in the examples you can see more about how to use it: https://github.com/rogelio-o/vertx-grpc-protoc-plugin/tree/master/examples

**Comment by indiketa** [comment] 2019-08-06 17:13
@vietj i think i've finished the approach. As you requested, i have generated a complete example of plugin usage.

https://github.com/indiketa/vertx-grpc-plugin-example

I would like to know (if possible) what lacks to the plugin to be a good candidate to replace the complicated vertx-grpc compiler or what can i do to make it better.

Thank your

**Comment by vietj** [comment] 2019-08-08 07:46
note for community: @rogelio-o does not use the salesforce compiler directly but is using some code of the salesforce plugin (https://github.com/rogelio-o/vertx-grpc-protoc-plugin/blob/master/vertx-grpc-protoc-plugin/src/main/java/io/vertx/grpc/protoc/plugin/VertxGrpcGenerator.java) and it looks like @indiketa did fork these classes

**Comment by vietj** [comment] 2019-08-08 07:49
@rogelio-o @indiketa it seems your efforts are very similar to me in their approach. Can we work on an approach where you guys contribute to the same effort, because at the end of the day we can only have one :-)

what I like a lot in your approach is that it seems very maintainable

**Comment by rogelio-o** [comment] 2019-08-08 15:20
Sure! How do you propose to do it?

I think important things in the implementation should be:
- Do the plugin as a protocPlugin
- Delegate through the original grpc implementation
- Implement the “bridge” between Vertx components and original grpc in utils classes in order to reduce the code placed in the stubs. This utils class should be in the vertx-grpc library

I also propose to make the vertx-grpc repository a multi module repository and l place the plugin also there.

**Comment by vietj** [comment] 2019-08-08 16:05
I agree with your points, delegating to original RPC allows us to maintain less code.

for the multi module we can see later.

**Comment by indiketa** [comment] 2019-08-09 15:42
@vietj All code was forked from reactive-grpc and jprotoc projects directly from salesforce. It was quite easy transform the 5 salesforce overpartitioned projects into one single maintainable project.

I agree with all you @rogelio-o: doing as protocPlugin and delegating to grpc

Because I do not have enough time, I will abandon my approach and I will try to reproduce my example into rogelio's branch. If I see that I can contribute with something, it will be. I'll test on Monday.

**Comment by vietj** [comment] 2019-08-09 16:26
thanks @indiketa

**Comment by vietj** [comment] 2019-08-09 16:27
I would like to see if we can somehow generate `@VertxGen` interface so we can then use this compiler along with Vert.x codegen and produce RxJava / Kotlin coroutine interfaces

**Comment by indiketa** [comment] 2019-08-13 10:57
I have been trying the @rogelio-o  proposal. 
The manyMany grpc method stubs (client and server) are generated as:

`public ReadStream<ExampleResponse> manyMany(ReadStream<ExampleRequest> request) `

I think it would be more natural and understandable to have:
Client stub: 
`public ReadStream<ExampleResponse> manyMany(WriteStream<ExampleRequest> request) `

Server stub: 
`public void manyMany(ReadStream<ExampleRequest> request, WriteStream<ExampleRequest> response) `

This makes implementation more easier and clear. In most cases the grpc output will be generated from the input. In the case of channels were independent, the developer always will be able to use a `Pipe`.

Otherwise the developer is forced to implement his own ReadStream to send the response (readstream to send response, it sounds weird). In order to implement the tests, this construction has already been used:

[`ManualReadStream`](https://github.com/rogelio-o/vertx-grpc/commits/issues/15-support-for-rxgrpc/vertx-grpc/src/test/java/io/vertx/ext/grpc/utils/ManualReadStream.java): A ReadStream that has a `send` method (extracted from test classes).

This applies to all streaming requests / responses (one to many, many to many, many to one)
The endpoint who sends a streaming, i think it should receive a WriterStream.

**Comment by ctrlshp** [comment] 2019-08-19 12:16
Hello, I too would like to see this happen. Is there any way I can help, even if it is just for testing ? If so where should I start ?

**Comment by vietj** [comment] 2019-08-19 16:29
thanks for your feedback @indiketa I think we could push @rogelio-o branch in this repo as a shared work branch where people can make PR's to help

**Comment by vietj** [comment] 2019-08-19 16:30
@rogelio-o can you make a PR against this repo for creating such branch ?

**Comment by rogelio-o** [comment] 2019-08-19 17:28
> @rogelio-o can you make a PR against this repo for creating such branch ?

Sure! Just let me know the branch where to merge it. I created the PR #42, I can change master to that shared work branch in the PR.

**Comment by vietj** [comment] 2019-08-19 17:35
I'll push directly from #42 to a branch then

**Comment by vietj** [comment] 2019-08-19 17:38
here is the branch https://github.com/vert-x3/vertx-grpc/tree/15-support-for-rxgrpc

**Comment by vietj** [comment] 2019-08-20 05:12
I made a draft PR for this branch https://github.com/vert-x3/vertx-grpc/pull/45 so it can be discussed, @indiketa feel free doing PR on this branch so when it's merged it will update the draft PR

**Comment by vietj** [comment] 2019-08-22 09:34
the other benefit of @indiketa change is that it is easy for make stream operation async with a pipe, i.e one can write:

```
Pipe<?> pipe = request.pipe();
vertx.setTimer(10, id -> {
  pipe.to(response);
});
```

**Comment by vietj** [comment] 2019-08-28 14:46
contribution from @indiketa has been merged

**Comment by pmlopes** [comment] 2020-07-30 18:56
New compiler has been merged

**Closed by pmlopes** 2020-07-30 18:56 UTC
Labels: good first issue
